# Generated by Django 4.0.4 on 2022-05-01 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_number', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(1)])),
                ('high_school', models.CharField(max_length=50)),
                ('school_address', models.CharField(max_length=50)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('if_transferee', models.BooleanField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
