# Generated by Django 4.0.4 on 2022-05-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='exam_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
