# Generated by Django 4.0.4 on 2022-05-01 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_datecreated_studentlist_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='contact_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
