# Generated by Django 4.0.4 on 2022-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_previousuniversity_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='enrolment_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
