# Generated by Django 4.0.4 on 2022-05-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_studentlist_enrolment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentlist',
            options={'verbose_name': 'Student'},
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='enrolment_status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
