# Generated by Django 4.0.4 on 2022-05-01 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_studentlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='contact_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='year',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(1), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
