# Generated by Django 4.0.4 on 2022-05-01 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_studentlist_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='contact_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='year',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(1)]),
        ),
    ]
