# Generated by Django 4.0.4 on 2022-05-04 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_studentlist_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlist',
            name='steward_city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='steward_contact_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)], verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='steward_country',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='steward_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='steward_home_address',
            field=models.CharField(max_length=50, null=True, verbose_name='Home Address'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='steward_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='steward_relationship',
            field=models.CharField(max_length=20, null=True, verbose_name='Relationship'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='steward_sex',
            field=models.CharField(max_length=10, null=True, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='uni_address',
            field=models.CharField(max_length=50, null=True, verbose_name='University Address'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='uni_city',
            field=models.CharField(max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='uni_country',
            field=models.CharField(max_length=50, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='studentlist',
            name='uni_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='contact_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Applied'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='enrolment_status',
            field=models.CharField(default='PENDING', max_length=10, verbose_name='Enrolment Status'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='exam_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Exam Number'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='gpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0), django.core.validators.MinValueValidator(0.0)], verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='high_school',
            field=models.CharField(max_length=50, verbose_name='High School'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='home_address',
            field=models.CharField(max_length=50, verbose_name='Home Address'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='if_transferee',
            field=models.BooleanField(null=True, verbose_name='If Transferee'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='school_address',
            field=models.CharField(max_length=50, verbose_name='School Address'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='year',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
