# Generated by Django 4.0.4 on 2022-05-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_studentlist_steward_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentList',
        ),
    ]
