# Generated by Django 4.0.4 on 2022-05-04 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0012_delete_studentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('exam_number', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Exam Number')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('birthdate', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=50, verbose_name='Home Address')),
                ('contact_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)], verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254)),
                ('college', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=50, verbose_name='Program')),
                ('year', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('high_school', models.CharField(max_length=50, verbose_name='High School')),
                ('school_address', models.CharField(max_length=50, verbose_name='School Address')),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0), django.core.validators.MinValueValidator(0.0)], verbose_name='GPA')),
                ('enrolment_status', models.CharField(default='PENDING', max_length=10, verbose_name='Enrolment Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Applied')),
                ('steward_name', models.CharField(max_length=50, verbose_name='Name')),
                ('steward_sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, verbose_name='Sex')),
                ('steward_relationship', models.CharField(max_length=20, verbose_name='Relationship')),
                ('steward_country', models.CharField(max_length=50, verbose_name='Country')),
                ('steward_city', models.CharField(max_length=50, verbose_name='City')),
                ('steward_home_address', models.CharField(max_length=50, verbose_name='Home Address')),
                ('steward_contact_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)], verbose_name='Contact Number')),
                ('steward_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('if_transferee', models.BooleanField(default=True, verbose_name='If Transferee')),
                ('uni_name', models.CharField(max_length=50, verbose_name='Name')),
                ('uni_country', models.CharField(max_length=50, verbose_name='Country')),
                ('uni_city', models.CharField(max_length=50, verbose_name='City')),
                ('uni_address', models.CharField(max_length=50, verbose_name='University Address')),
                ('uni_college', models.CharField(max_length=20, verbose_name='Previous College')),
                ('uni_course', models.CharField(max_length=50, verbose_name='Previous Program')),
                ('uni_year', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Previous Year')),
                ('uni_reason', models.TextField(verbose_name='Reason of Transfer')),
            ],
            options={
                'verbose_name': 'Student',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
