# Generated by Django 4.0.4 on 2022-05-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
