# Generated by Django 4.0.4 on 2022-05-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_studentlist_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='birthdate',
            field=models.DateField(help_text='Follow this format: YYYY-MM-DD', verbose_name='Birthdate'),
        ),
    ]
