# Generated by Django 4.0.4 on 2022-05-14 02:01

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_studentlist_high_school_alter_studentlist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='name',
            field=models.CharField(help_text='Follow this format: LastName, FirstName MiddleName', max_length=50, validators=[main.validators.validate_names, main.validators.validate_name_format], verbose_name='Name:'),
        ),
    ]
