# Generated by Django 4.0.4 on 2022-05-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
