# Generated by Django 4.0.4 on 2022-05-29 16:30

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_studentlist_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlist',
            name='uni_college',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[main.validators.validate_names], verbose_name='Previous College'),
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='uni_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Previous Program'),
        ),
    ]
